//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Entity.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class KidsApp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KidsApp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Entity.Resources.KidsApp", typeof(KidsApp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skillaround is a one stop location for all activities and educational material for all kids. The system will give an opportunity for parents to search activities based on categories, locations and ages..
        /// </summary>
        public static string AboutEmailBody {
            get {
                return ResourceManager.GetString("AboutEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Your Account.
        /// </summary>
        public static string ActivateYourAccount {
            get {
                return ResourceManager.GetString("ActivateYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Client Chosen Location.
        /// </summary>
        public static string AtUserLocation {
            get {
                return ResourceManager.GetString("AtUserLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Details.
        /// </summary>
        public static string BookingDetails {
            get {
                return ResourceManager.GetString("BookingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply to your inquery.
        /// </summary>
        public static string ContactUsReply {
            get {
                return ResourceManager.GetString("ContactUsReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Email.
        /// </summary>
        public static string EmailMessageSubject {
            get {
                return ResourceManager.GetString("EmailMessageSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest Password.
        /// </summary>
        public static string EmailResetPasswodSubject {
            get {
                return ResourceManager.GetString("EmailResetPasswodSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoTo My Portal.
        /// </summary>
        public static string GoToMyPortal {
            get {
                return ResourceManager.GetString("GoToMyPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Booking.
        /// </summary>
        public static string NewBooking {
            get {
                return ResourceManager.GetString("NewBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnLine.
        /// </summary>
        public static string OnlineLocation {
            get {
                return ResourceManager.GetString("OnlineLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password? No worries, we’ve got you covered. Click the link below to reset your password..
        /// </summary>
        public static string ResetPasswordEmailHeader {
            get {
                return ResourceManager.GetString("ResetPasswordEmailHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPasswordSubject {
            get {
                return ResourceManager.GetString("ResetPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sent you a message.
        /// </summary>
        public static string SentYouEmail {
            get {
                return ResourceManager.GetString("SentYouEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Message.
        /// </summary>
        public static string SentYouEmailSubject {
            get {
                return ResourceManager.GetString("SentYouEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set New Password.
        /// </summary>
        public static string SetNewPassword {
            get {
                return ResourceManager.GetString("SetNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for signing up with us. now you can search for Unique and Special activities..
        /// </summary>
        public static string WelcomeEmailSubTitle {
            get {
                return ResourceManager.GetString("WelcomeEmailSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for Registering with us. your documents has been submmited for review, now you can start managing your own activities..
        /// </summary>
        public static string WelcomeEmailSupplierSubTitle {
            get {
                return ResourceManager.GetString("WelcomeEmailSupplierSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To Skillaround.
        /// </summary>
        public static string WelcomEmailSubject {
            get {
                return ResourceManager.GetString("WelcomEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message.
        /// </summary>
        public static string YourMessage {
            get {
                return ResourceManager.GetString("YourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username is.
        /// </summary>
        public static string YouUserNameIs {
            get {
                return ResourceManager.GetString("YouUserNameIs", resourceCulture);
            }
        }
    }
}
